local Plug = vim.fn['plug#']
vim.call('plug#begin', '~/.config/nvim/plugged')

Plug 'neovim/nvim-lspconfig'
Plug 'lukas-reineke/lsp-format.nvim'
Plug 'onsails/lspkind.nvim'

Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-treesitter/playground'

Plug 'L3MON4D3/LuaSnip'

Plug 'David-Kunz/cmp-npm'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-cmdline'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/cmp-nvim-lsp-signature-help'
-- Plug 'hrsh7th/cmp-nvim-lsp-document-symbol'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/nvim-cmp'
Plug 'petertriho/cmp-git'
Plug 'saadparwaiz1/cmp_luasnip'

Plug 'nvim-telescope/telescope.nvim'
--Plug 'nvim-telescope/telescope-media-files.nvim'
--Plug 'nvim-telescope/telescope-fzf-native.nvim'

Plug 'AckslD/nvim-neoclip.lua'
Plug 'AndrewRadev/tagalong.vim'
Plug 'ThePrimeagen/harpoon'
Plug 'TimUntersberger/neogit'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ellisonleao/glow.nvim'
Plug 'fatih/vim-go'
Plug 'folke/todo-comments.nvim'
Plug 'folke/trouble.nvim'
Plug 'folke/twilight.nvim'
Plug 'folke/which-key.nvim'
Plug 'goolord/alpha-nvim'
Plug 'gpanders/editorconfig.nvim'
Plug 'iamcco/markdown-preview.nvim'
Plug 'kyazdani42/nvim-tree.lua'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'lewis6991/gitsigns.nvim'
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'norcalli/nvim-colorizer.lua'
Plug 'numToStr/Comment.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lualine/lualine.nvim'
Plug 'petertriho/nvim-scrollbar'
Plug 'prettier/vim-prettier'
Plug 'pwntester/octo.nvim'
Plug 'rmagatti/goto-preview'
Plug 'romgrk/barbar.nvim'
Plug 'simrat39/symbols-outline.nvim'
Plug 'sindrets/diffview.nvim'
Plug 'sudormrfbin/cheatsheet.nvim'
Plug 'sunjon/shade.nvim'
Plug 'windwp/nvim-autopairs'
--Plug 'mg979/vim-visual-multi'
--Plug 'mbbill/undotree'
--Plug 'akinsho/toggleterm.nvim'
--Plug 'nvim-lua/popup.nvim'
--Plug 'ziontee113/color-picker.nvim'
--Plugin 'dbeniamine/cheat.sh-vim'

--Plug 'MunifTanjim/nui.nvim'
--Plug 'folke/noice.nvim'
--Plug 'rcarriga/nvim-notify'

Plug 'mfussenegger/nvim-dap'
Plug 'rcarriga/nvim-dap-ui'
Plug 'theHamsta/nvim-dap-virtual-text'
Plug 'mxsdev/nvim-dap-vscode-js'
--Plug 'nvim-telescope/telescope-dap.nvim'

Plug 'cakebaker/scss-syntax.vim'
Plug 'tikhomirov/vim-glsl'
--Plug 'chr4/nginx.vim'

Plug 'vimwiki/vimwiki'

Plug 'navarasu/onedark.nvim'

Plug '~/dev/nvim/nvhx'
Plug '~/dev/nvim/nvim-twodark'
--Plug '~/dev/nvim/nvim-xmpp'
--Plug '~/dev/nvim/nvim-cmp-haxelib'

vim.call('plug#end')
